"""Credential-free data source and analyzer.

The mock source generates a deterministic but realistic channel — uneven view
counts, a few outliers, mixed Shorts and long-form, gaps in the upload schedule,
and transcripts missing for some videos, exactly as the real API behaves. That
makes the analytics tests meaningful rather than trivially green.
"""

from __future__ import annotations

import random
import re
from collections import Counter
from datetime import datetime, timedelta, timezone
from typing import List, Optional

from ..config import Settings
from ..models import (
    Channel,
    ContentInsights,
    Transcript,
    TranscriptSegment,
    Video,
)
from .base import ContentAnalyzer, DataSource, ProviderError, register_analyzer, register_source

#: Fixed so every mock run produces byte-identical output.
SEED = 20260811

TITLE_TEMPLATES = [
    "How {topic} Actually Works (No Hype)",
    "I Built {topic} in {n} Hours",
    "{topic} Explained in {n} Minutes",
    "Stop Using {topic} Wrong",
    "The Truth About {topic}",
    "{n} {topic} Mistakes Everyone Makes",
    "{topic}: What Nobody Tells You",
    "Building a Production {topic} Pipeline",
    "Why {topic} Is Harder Than It Looks",
    "{topic} vs The Alternatives — Honest Comparison",
]

TOPICS = [
    "RAG", "Vector Databases", "LangChain", "Fine-Tuning", "Prompt Engineering",
    "LLM Agents", "Embeddings", "Whisper", "Model Evaluation", "Quantization",
    "Streamlit Apps", "FastAPI Backends", "Hugging Face", "Semantic Search",
]

TAG_POOL = [
    "ai", "machine learning", "llm", "python", "tutorial", "rag", "langchain",
    "openai", "gemini", "vector database", "nlp", "deep learning", "coding",
    "data science", "agents",
]

HOOKS = [
    "Everyone gets this wrong, and it costs them weeks.",
    "In the next few minutes you'll understand exactly why this breaks.",
    "I spent three months on this so you don't have to.",
    "Let me show you the version that actually ships to production.",
    "This one change cut our latency by more than half.",
]

BODY_SENTENCES = [
    "The core idea is simpler than the documentation makes it look.",
    "Start with the smallest thing that works, then measure before optimising.",
    "Most tutorials skip the failure cases, which is where the real work is.",
    "Retrieval quality bounds everything downstream, so fix that first.",
    "Latency and cost are the constraints nobody plans for until production.",
    "Evaluation is boring and it is the only thing that tells you if this works.",
    "You do not need a bigger model, you need better inputs.",
    "Chunking strategy matters more than the embedding model you pick.",
]


class MockDataSource(DataSource):
    """Generates a deterministic synthetic channel for offline runs."""

    name = "mock"
    CHANNEL_ID = "UCmock000000000000000000"

    def resolve_channel(self, identifier: str) -> Channel:
        if not (identifier or "").strip():
            raise ProviderError("Channel identifier must not be empty.")

        return Channel(
            id=self.CHANNEL_ID,
            title="Build With AI (demo channel)",
            description=(
                "Practical engineering walkthroughs for LLM applications: "
                "retrieval, agents, evaluation and shipping to production. "
                "This is synthetic data generated by the mock provider."
            ),
            subscriber_count=48_200,
            video_count=137,
            view_count=4_812_000,
            uploads_playlist_id="UUmock000000000000000000",
            published_at=datetime(2021, 6, 14, tzinfo=timezone.utc),
            thumbnail_url="https://example.invalid/mock-channel.jpg",
        )

    def fetch_videos(self, channel: Channel, limit: int) -> List[Video]:
        rng = random.Random(SEED)
        # A fixed "now" keeps generated dates stable across runs.
        anchor = datetime(2026, 8, 1, tzinfo=timezone.utc)
        videos: List[Video] = []
        days_back = 0
        for index in range(min(limit, 60)):
            topic = TOPICS[index % len(TOPICS)]
            template = TITLE_TEMPLATES[index % len(TITLE_TEMPLATES)]
            title = template.format(topic=topic, n=rng.choice([3, 5, 7, 10]))

            is_short = index % 7 == 0
            duration = rng.randint(20, 58) if is_short else rng.randint(360, 1500)

            # Gaps accumulate backwards from the anchor: roughly weekly, with
            # enough variance that the consistency score isn't a perfect 100.
            published = anchor - timedelta(days=days_back)
            days_back += rng.choice([4, 5, 6, 9, 12])

            base_views = rng.randint(4_000, 40_000)
            # Two reliable outliers, so outlier detection has something to find.
            if index in (3, 11):
                base_views *= rng.randint(6, 12)

            like_rate = rng.uniform(0.02, 0.06)
            comment_rate = rng.uniform(0.001, 0.005)

            videos.append(
                Video(
                    id=f"mockvid{index:04d}",
                    title=title,
                    description=f"A practical walkthrough of {topic}.",
                    published_at=published,
                    duration_seconds=duration,
                    view_count=base_views,
                    like_count=int(base_views * like_rate),
                    comment_count=int(base_views * comment_rate),
                    tags=rng.sample(TAG_POOL, rng.randint(3, 7)),
                    thumbnail_url=f"https://example.invalid/thumb{index}.jpg",
                )
            )

        return videos

    def fetch_transcript(self, video: Video) -> Transcript:
        # Roughly a third of videos have no transcript, as on real channels.
        if hash(video.id) % 3 == 0:
            return Transcript(video_id=video.id, error="TranscriptsDisabled")

        rng = random.Random(SEED + len(video.id) + video.view_count)
        segments: List[TranscriptSegment] = []
        cursor = 0.0

        hook = rng.choice(HOOKS)
        segments.append(TranscriptSegment(start=0.0, duration=6.0, text=hook))
        cursor = 6.0

        sentence_count = max(4, min(video.duration_seconds // 45, 18))
        for _ in range(sentence_count):
            sentence = rng.choice(BODY_SENTENCES)
            duration = rng.uniform(4.0, 9.0)
            segments.append(
                TranscriptSegment(start=cursor, duration=duration, text=sentence)
            )
            cursor += duration

        return Transcript(
            video_id=video.id, segments=segments, language="en", is_generated=True
        )


class HeuristicAnalyzer(ContentAnalyzer):
    """Rule-based content insights. Deterministic, offline, no API key."""

    name = "mock"

    def analyze(
        self,
        channel: Channel,
        videos: List[Video],
        transcripts: List[Transcript],
    ) -> Optional[ContentInsights]:
        if not videos:
            return None

        return ContentInsights(
            themes=self._themes(videos),
            hook_patterns=self._hook_patterns(transcripts),
            content_format=self._format(videos),
            target_audience=self._audience(videos),
            strengths=self._strengths(videos),
            opportunities=self._opportunities(videos),
            recommended_topics=self._recommendations(videos),
        )

    # -- components ---------------------------------------------------------

    @staticmethod
    def _themes(videos: List[Video]) -> List[str]:
        counter: Counter = Counter()
        for video in videos:
            counter.update({tag.lower() for tag in video.tags})
        return [tag.title() for tag, _ in counter.most_common(6)]

    @staticmethod
    def _hook_patterns(transcripts: List[Transcript]) -> List[str]:
        openings = [t.opening(20) for t in transcripts if t.available]
        openings = [opening for opening in openings if opening]
        if not openings:
            return []

        patterns = []
        if any(re.search(r"\byou\b", opening, re.I) for opening in openings):
            patterns.append("Addresses the viewer directly in the first sentence")
        if any(re.search(r"\d", opening) for opening in openings):
            patterns.append("Leads with a concrete number or timeframe")
        if any(
            re.search(r"\b(wrong|mistake|nobody|truth|costs)\b", opening, re.I)
            for opening in openings
        ):
            patterns.append("Opens on a contrarian or corrective claim")
        if any(
            re.search(r"\b(I|we) (built|spent|tried)\b", opening) for opening in openings
        ):
            patterns.append("Frames the video as first-hand experience")
        return patterns or ["Opens with a plain statement of the topic"]

    @staticmethod
    def _format(videos: List[Video]) -> str:
        shorts = sum(1 for video in videos if video.is_short)
        share = shorts / len(videos) * 100
        longform = [v.duration_seconds for v in videos if not v.is_short]
        mean_minutes = (sum(longform) / len(longform) / 60) if longform else 0

        if share > 60:
            return f"Shorts-first channel ({share:.0f}% of uploads are under a minute)"
        if share < 10:
            return f"Long-form only, averaging about {mean_minutes:.0f} minutes"
        return (
            f"Mixed format: {share:.0f}% Shorts alongside long-form averaging "
            f"about {mean_minutes:.0f} minutes"
        )

    @staticmethod
    def _audience(videos: List[Video]) -> str:
        tags = {tag.lower() for video in videos for tag in video.tags}
        technical = {"python", "coding", "machine learning", "deep learning", "nlp", "llm"}
        if tags & technical:
            return (
                "Practising developers and ML engineers building LLM "
                "applications, not beginners looking for an introduction"
            )
        return "General audience interested in the channel's subject area"

    @staticmethod
    def _strengths(videos: List[Video]) -> List[str]:
        from ..analytics import consistency_score, outliers

        strengths = []
        score = consistency_score(videos)
        if score is not None and score > 60:
            strengths.append(
                f"Upload cadence is regular (consistency score {score:.0f}/100)"
            )

        top = outliers(videos)
        if top:
            strengths.append(
                f"{len(top)} video(s) substantially outperform the median — "
                f"the best is '{top[0].title}'"
            )

        engaged = [v for v in videos if v.engagement_rate > 4.0]
        if engaged:
            strengths.append(
                f"{len(engaged)} video(s) clear a 4% engagement rate, well above "
                f"the platform norm"
            )
        return strengths or ["Consistent topical focus across the catalogue"]

    @staticmethod
    def _opportunities(videos: List[Video]) -> List[str]:
        from ..analytics import consistency_score

        opportunities = []

        untagged = [video for video in videos if not video.tags]
        if untagged:
            opportunities.append(
                f"{len(untagged)} video(s) have no tags at all, which costs "
                f"discoverability for free"
            )

        score = consistency_score(videos)
        if score is not None and score < 50:
            opportunities.append(
                f"Upload spacing is irregular (consistency score {score:.0f}/100) — "
                f"a predictable schedule compounds"
            )

        shorts = sum(1 for video in videos if video.is_short)
        if shorts == 0:
            opportunities.append(
                "No Shorts at all — the format is the cheapest discovery surface "
                "available"
            )

        titles = [video.title for video in videos]
        if len(set(titles)) < len(titles):
            opportunities.append("Duplicate titles are competing with each other")

        return opportunities or ["No structural gaps stand out in this sample"]

    @staticmethod
    def _recommendations(videos: List[Video]) -> List[str]:
        from ..analytics import outliers

        top = outliers(videos) or sorted(
            videos, key=lambda video: -video.view_count
        )[:2]

        recommendations = []
        for video in top[:3]:
            subject = re.sub(
                r"^(how|why|the|stop|i built|building a)\b\s*", "", video.title,
                flags=re.IGNORECASE,
            ).strip()
            recommendations.append(f"A follow-up going deeper on: {subject}")
        return recommendations


register_source("mock", MockDataSource)
register_analyzer("mock", HeuristicAnalyzer)
